blueprint:
  name: Actions for 6-Button Homematic(IP) device
  description: When a button is pressed, the defined actions will be executed. Please
    keep in mind, that long-press actions might be executed multiple times, according
    to your configured minimum duration for long press. This can be configured in
    your CCU.
  domain: automation
  source_url: https://github.com/danielperna84/custom_homematic/blob/devel/blueprints/automation/homematicip_local-actions-for-6-button.yaml
  input:
    remote:
      name: 6-Button Device
      description: Please select a 6-Button device of your Homematic(IP) Local integration.
      selector:
        device:
          integration: homematicip_local
    action_left_top_short:
      name: Action
      description: Left-Top-Button, Short Press
      default: []
      selector:
        action: {}
    action_left_top_long:
      name: Action
      description: Left-Top-Button, Long Press
      default: []
      selector:
        action: {}
    action_right_top_short:
      name: Action
      description: Right-Top-Button, Short Press
      default: []
      selector:
        action: {}
    action_right_top_long:
      name: Action
      description: Right-Top-Button, Long Press
      default: []
      selector:
        action: {}
    action_left_middle_short:
      name: Action
      description: Left-Middle-Button, Short Press
      default: []
      selector:
        action: {}
    action_left_middle_long:
      name: Action
      description: Left-Middle-Button, Long Press
      default: []
      selector:
        action: {}
    action_right_middle_short:
      name: Action
      description: Right-Middle-Button, Short Press
      default: []
      selector:
        action: {}
    action_right_middle_long:
      name: Action
      description: Right-Middle-Button, Long Press
      default: []
      selector:
        action: {}
    action_left_bottom_short:
      name: Action
      description: Left-Bottom-Button, Short Press
      default: []
      selector:
        action: {}
    action_left_bottom_long:
      name: Action
      description: Left-Bottom-Button, Long Press
      default: []
      selector:
        action: {}
    action_right_bottom_short:
      name: Action
      description: Right-Bottom-Button, Short Press
      default: []
      selector:
        action: {}
    action_right_bottom_long:
      name: Action
      description: Right-Bottom-Button, Long Press
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: homematic.keypress
  event_data:
    device_id: !input 'remote'
condition: []
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_left_top_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 1 }}'
    sequence: !input 'action_left_top_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_right_top_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 2 }}'
    sequence: !input 'action_right_top_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 3 }}'
    sequence: !input 'action_left_middle_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 3 }}'
    sequence: !input 'action_left_middle_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 4 }}'
    sequence: !input 'action_right_middle_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 4 }}'
    sequence: !input 'action_right_middle_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 5 }}'
    sequence: !input 'action_left_bottom_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 5 }}'
    sequence: !input 'action_left_bottom_long'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_short'' and trigger.event.data.subtype  == 6 }}'
    sequence: !input 'action_right_bottom_short'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.type  == ''press_long'' and trigger.event.data.subtype  == 6 }}'
    sequence: !input 'action_right_bottom_long'
mode: parallel
max: 10
